name: Deploy static content to Pages

on:
  push:
    branches: ['main'] # 본인의 기본 브랜치명이 master라면 'master'로 변경하세요.

# GitHub Pages 배포를 위해 GITHUB_TOKEN의 권한을 설정합니다.
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포가 일어날 경우 최신 버전만 유지합니다.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 사용 중인 Node.js 버전에 맞게 수정하셔도 됩니다.
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci # 패키지 매니저로 yarn을 쓰신다면 'yarn install'로 변경하세요.
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite의 기본 빌드 결과물 폴더입니다.
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
